### ISSUE TITLE
"Pointers cannot reference marshaled structures.  Use ByRef instead" caused by VariableLengthInlineArray

### ISSUE THREAD

**Issue by Nuklon** [microsoft/CsWin32#1218] opened 2024-06-24 11:25 UTC
## Actual behavior

Pointers cannot reference marshaled structures.  Use ByRef instead.
Only happens on .NET Framework 472.
If you remove the ```public global::Windows.Win32.VariableLengthInlineArray<char> HardwareID;``` field from `SP_DRVINFO_DETAIL_DATA_W` it works correctly. It worked correctly in CsWin32 [0.3.49](https://github.com/microsoft/CsWin32/releases/tag/v0.3.49-beta).

## Expected behavior

Work correctly.

## Repro steps

1. `NativeMethods.txt` content:
```
SetupDiGetDriverInfoDetail
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.3.106
- Win32Metadata version (if explicitly set by project): 61.0.15-preview
- Target Framework: net472

**Comment by Nuklon** [comment] 2024-06-24 13:08
If you include `System.Memory` package, the error instead becomes:
Error (active)	CS0117	'Unsafe' does not contain a definition for 'SkipInit'

**Comment by Zoraver** [comment] 2024-08-26 00:13
I am running into a similar issue when attempting to call `CM_Register_Notification` on .NET Framework 4.8 using CsWin32 0.3.106. This does not occur when targeting .NET 8.

**Comment by Zoraver** [comment] 2024-08-30 03:13
I believe that this issue is effectively a duplicate of #1184.

**Comment by AArnott** [comment] 2024-09-30 16:54
I can't get this to repro using the instructions given in this issue. But I agree with @zoraver that this is likely a duplicate of one that I _can_ repro. So I'm closing this.

**Closed by AArnott** 2024-09-30 16:54 UTC
Labels: bug

**Comment by Nuklon** [comment] 2024-10-01 14:02
Sorry, I forgot to add instructions on how to reproduce. I retried it and it's still present in latest daily. 

You need to call SetupDiGetDriverInfoDetail with the details from the device:

```
uint driverInfoDetailDataSize = (uint)sizeof(SP_DRVINFO_DETAIL_DATA_W) + (PInvoke.MAX_DEVICE_ID_LEN * 2);
IntPtr driverInfoDetailDataHandle = Marshal.AllocHGlobal((IntPtr)driverInfoDetailDataSize);

try
{
	var driverInfoDetailData = (SP_DRVINFO_DETAIL_DATA_W*)driverInfoDetailDataHandle;
	driverInfoDetailData->cbSize = (uint)sizeof(SP_DRVINFO_DETAIL_DATA_W);
	uint requiredSize = 0;

        // This call throws the above exception.
	if (PInvoke.SetupDiGetDriverInfoDetail(deviceInfoList, &deviceInfoData, &driverInfoData, driverInfoDetailData, driverInfoDetailDataSize, &requiredSize))
	{
		
	}
```

**Comment by AArnott** [comment] 2024-10-01 15:44
Thanks for that, @nuklon. My fix for the believed duplicate bug is in version 0.3.149, for which no daily build exists yet due to a temporary service outage during our last daily build. I've re-kicked it off. If you could please test your scenario with that and report back, I'd appreciate it.

**Comment by Nuklon** [comment] 2024-10-02 11:35
Thanks, I can confirm that it's working fine now with 0.3.149. Another workaround down 😁
