### ISSUE TITLE
Make COM interfaces easier to use

### ISSUE THREAD

**Issue by weltkante** [microsoft/CsWin32#86] opened 2021-02-13 20:54 UTC
Please correct me if I missed something, but if read the generated code correctly you generate structs for COM interfaces. These are neither compatible with GC nor using-statements, requiring manual reference counting again, which is very error prone (C++ uses smart pointers for a reason). If people store these COM references anywhere and their objects get GC'ed they'll leak COM references, and even if you remember to implement a finalizer it is nontrivial to get right because the finalizer will run in the wrong apartment and I doubt the average C# programmer considers this. IMHO this loooks like a terrible design, can we get a better projection for COM interfaces? Otherwise people will get reference counting, apartment handling and finalization wrong more often than not, leading to lots of bugs in production code ...

**Comment by reflectronic** [comment] 2021-02-14 03:24
Yeah, the 'raw' bindings are good for some things, but I think it would almost certainly be preferable to translate COM interfaces to to `ComImport` (or, perhaps, some custom `ComWrappers` solution) for C#/Win32. 

Some other project like [TerraFX.Interop.Windows](https://github.com/terrafx/terrafx.interop.windows) can be used if you require the performance and predictability of the raw bindings, e.g. if you are using D3D. (D3D is nano-COM anyway, so no marshaling concerns in sight.) It's even got a handy-dandy (and a slightly wonky) port of `ComPtr<T>` that uses `IDisposable`.

**Comment by AArnott** [comment] 2021-02-16 18:28
Yes, these are all great points.

Duplicate of #26 (and #79)

**Closed by AArnott** 2021-02-16 18:28 UTC
