### ISSUE TITLE
Using PROPVARIANT results in TypeLoadException

### ISSUE THREAD

**Issue by bastos80** [microsoft/CsWin32#211] opened 2021-03-17 20:42 UTC
As soon as my application loads the assembly I built using CsWin32 I get the following exception:

`Could not load type '_Anonymous_e__Union' from assembly '<my assembly utilizing CsWin32>' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.`

I mean, it's right to complain I guess, blittable types are unioned with managed types. But how would anyone ever be able to use the current generated Windows.Win32.StructuredStorage.PROPVARIANT if this is the case?

**Comment by AArnott** [comment] 2021-03-17 20:58
Duplicate of #197

Thanks for reporting. Till we can fix this, note the workaround here: https://github.com/microsoft/CsWin32/issues/197#issuecomment-800652260

**Closed by AArnott** 2021-03-17 20:58 UTC
