### ISSUE TITLE
Missing safehandle overload for GetWindowDC (User32) CreateCompatibleDC (Gdi32)

### ISSUE THREAD

**Issue by josdemmers** [microsoft/CsWin32#485] opened 2022-01-23 16:59 UTC
**Is your feature request related to a problem? Please describe.**
Related functions do not return a SafeHandle while it is required as input for the other function.
See code example below.
Both PInvoke.GetWindowDC and PInvoke.CreateCompatibleDC do not return a SafeHandle while PInvoke.BitBlt expects a SafeHandle as input.

**Describe the solution you'd like**
Overloaded function that does return a Safehandle.

**Additional context**
Code example showing the issue:
```
public Bitmap GetScreenCapture(IntPtr handle)
    {
      Bitmap bitmap;

      Windows.Win32.Foundation.RECT region;
      PInvoke.GetWindowRect((Windows.Win32.Foundation.HWND)handle, out region);

      var desktopWindowHandle = PInvoke.GetDesktopWindow();
      var windowDCHandle = PInvoke.GetWindowDC(desktopWindowHandle);
      var memoryDCHandle = PInvoke.CreateCompatibleDC(windowDCHandle);
      var bitmapHandle =  PInvoke.CreateCompatibleBitmap(windowDCHandle, region.right - region.left, region.bottom - region.top);
      var bitmapOldHandle = PInvoke.SelectObject(memoryDCHandle, bitmapHandle);

      bool status = PInvoke.BitBlt(memoryDCHandle, 0, 0, region.right - region.left, region.bottom - region.top, windowDCHandle, region.left, region.top, Windows.Win32.Graphics.Gdi.ROP_CODE.SRCCOPY | Windows.Win32.Graphics.Gdi.ROP_CODE.CAPTUREBLT);

      try
      {
        bitmap = Image.FromHbitmap(bitmapHandle);
      }
      finally
      {
        PInvoke.SelectObject(memoryDCHandle, bitmapOldHandle);
        PInvoke.DeleteObject(bitmapHandle);
        PInvoke.DeleteDC(memoryDCHandle);
        PInvoke.ReleaseDC(desktopWindowHandle, windowDCHandle);
      }

      return bitmap;
    }

    public void WriteBitmapToFile(string filename, Bitmap bitmap)
    {
      bitmap.Save(filename, ImageFormat.Jpeg);
    }
}
```

**Comment by AArnott** [comment] 2022-01-25 22:54
This is a dupe of #209, although it may not immediately be obvious why. `ReleaseDC` is an odd release method in that it takes *two* parameters, so it will require special casing in CsWin32. Once that's done, `GetWindowDC` will automatically get a `SafeHandle`-returning method.
`CreateCompatibleDC` already has a `SafeHandle` overload but it isn't selected by the compiler because of the `GetWindowsDC` return-type. 

Here is how your code looks after #209 is fixed:

```cs
using System.Drawing;
using System.Runtime.InteropServices;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using static Windows.Win32.PInvoke;

class Helper
{
    public Bitmap GetScreenCapture(HWND handle)
    {
        Bitmap bitmap;

        RECT region;
        GetWindowRect(handle, out region);

        HWND desktopWindowHandle = GetDesktopWindow();
        using SafeHandle windowDCHandle = GetWindowsDC_SafeHandle(desktopWindowHandle);
        using DeleteDCSafeHandle memoryDCHandle = CreateCompatibleDC(windowDCHandle);
        using DeleteObjectSafeHandle bitmapHandle = CreateCompatibleBitmap(windowDCHandle, region.right - region.left, region.bottom - region.top);
        HGDIOBJ bitmapOldHandle = SelectObject(memoryDCHandle, (HGDIOBJ)bitmapHandle.DangerousGetHandle());

        bool success = BitBlt(memoryDCHandle, 0, 0, region.right - region.left, region.bottom - region.top, windowDCHandle, region.left, region.top, ROP_CODE.SRCCOPY | ROP_CODE.CAPTUREBLT);

        try
        {
            bitmap = Image.FromHbitmap(bitmapHandle.DangerousGetHandle());
        }
        finally
        {
            SelectObject(memoryDCHandle, bitmapOldHandle);
        }

        return bitmap;
    }
}

namespace Windows.Win32
{
    partial class PInvoke
    {
        internal static SafeHandle GetWindowsDC_SafeHandle(HWND hwnd)
        {
            return null;
        }
    }
}
```

The remaining bit that makes me wish for something better is this line:

```cs
HGDIOBJ bitmapOldHandle = SelectObject(memoryDCHandle, (HGDIOBJ)bitmapHandle.DangerousGetHandle());
```

I don't like the second argument and wish `SelectObject` had an overload that took a `SafeHandle`. For that, we would need `HGDIOBJ` to be recognized as a struct that sometimes takes the form of a `SafeHandle`. I filed #491 to track that.

**Closed by AArnott** 2022-01-25 22:54 UTC
Labels: enhancement

**Comment by josdemmers** [comment] 2022-01-26 09:09
Great, thank you for your time. I see that you are both active on the pinvoke and CsWin32 package. Looking forward to future updates.
