### ISSUE TITLE
AlsoUsableForAttribute should drive handle struct conversions and SafeHandle overloads

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#205] opened 2021-03-17 14:46 UTC
Using CsWin32 0.1.422-beta, not referencing the metadata package directly.
This seems to be the required workaround:

```cs
// Leaving out DangerousAddRef etc which should generally be added reflexively whenever DangerousGetHandle is used
PInvoke.SelectObject(bitmapDC, (HGDIOBJ)bitmap.DangerousGetHandle());
```

I'd expect DangerousGetHandle management to be done for me:
```cs
PInvoke.SelectObject(bitmapDC, bitmap);
```

`bitmap` is a `DeleteObjectSafeHandle` field that is assigned from a call to `CreateDIBSection`.

**Comment by AArnott** [comment] 2021-03-17 15:02
`CreateDIBSection` returns `HBITMAP` which is freeable via `DeleteObject`, so `CreateDIBSection` offers a `SafeHandle`.

`HGDIOBJ` is not a releasable handle, per the metadata. That's why we don't expose a SafeHandle overload of this method.

With the next metadata update, `HGDIOBJ` will be [recognized as a kind of base type](https://github.com/microsoft/win32metadata/commit/ef2ab15110d8e0c5125abb6d951890e094a63fcd) for several other typedef structs, including `HBITMAP`. At that point we should make some changes in the CsWin32 projection to not only add conversion operators between these structs, but also to accept `SafeHandle` everywhere that accepts `HGDIOBJ`.

**Comment by AArnott** [comment] 2021-03-17 15:15
Duplicate of #199

**Closed by AArnott** 2021-03-17 15:15 UTC
Labels: enhancement
