### ISSUE TITLE
WerReportCreate should return a SafeHandle type for phReportHandle

### ISSUE THREAD

**Issue by palenshus** [microsoft/CsWin32#413] opened 2021-09-20 18:23 UTC
## Actual behavior

Current function returns a `nint` in the `phReportHandle` parameter:

```cs
internal static unsafe win32.Foundation.HRESULT WerReportCreate(..., out nint phReportHandle)
```

## Expected behavior

`phReportHandle` should be a `SafeHandle` derived type, ideally one that derives from `SafeHandleZeroOrMinusOneIsInvalid` and calls `WerReportCloseHandle` on `ReleaseHandle()`:

```cs
        /// <summary>
        /// Wraps HREPORT value returned by <see cref="NativeMethods.WerReportCreate"/>.
        /// </summary>
        private class ReportHandle : Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid
        {
            private ReportHandle()
                : base(true /* ownsHandle */)
            {
            }

            public static implicit operator nint(ReportHandle h) => h.handle;

            protected override bool ReleaseHandle()
            {
                return PInvoke.WerReportCloseHandle(this.handle) == 0;
            }
        }
```

## Repro steps

1. `NativeMethods.txt` content:
```
WerReportCreate
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

CsWin32 version: 0.1.588-beta
Target Framework: .NET 5.0

**Comment by AArnott** [comment] 2021-09-22 17:35
Duplicate of https://github.com/microsoft/win32metadata/issues/655

**Closed by AArnott** 2021-09-22 17:35 UTC
Labels: bug

**Comment by palenshus** [comment] 2021-09-22 17:57
Ah nice, you're way ahead of me :)
