### ISSUE TITLE
Regression for `CreateFileW` (no `FILE_ACCESS_FLAG` enum)

### ISSUE THREAD

**Issue by alexrp** [microsoft/CsWin32#914] opened 2023-04-11 18:50 UTC
## Actual behavior

![image](https://user-images.githubusercontent.com/44076/231259958-8e4672c5-5628-48f6-928c-78304a123055.png)
![image](https://user-images.githubusercontent.com/44076/231260008-66edfe9c-dd7d-497b-aafa-302422bd436b.png)

I suspect that this might actually be a Win32Metadata issue, since various other APIs still get their associated enums as expected, but filing this here as I'm unsure.

## Expected behavior

This code used to work. The enum seems to have vanished.

## Repro steps

1. `NativeMethods.txt` content:
```
CreateFileW
```

2. `NativeMethods.json` content (if present):
```json
{
  "className": "WindowsPInvoke",
  "allowMarshaling": false,
  "wideCharOnly": false,
  "emitSingleFile": true
}
```

### Context

- CsWin32 version: 0.2.206-beta
- Win32Metadata version (if explicitly set by project): 48.0.19-preview
- Target Framework: net7.0
- LangVersion (if explicitly set by project): latest

**Comment by AArnott** [comment] 2023-04-11 18:58
Duplicate of #893

**Closed by AArnott** 2023-04-11 18:58 UTC
Labels: bug
