### ISSUE TITLE
New lines in generated code :)

### ISSUE THREAD

**Issue by zgabi** [microsoft/CsWin32#118] opened 2021-02-17 16:29 UTC
Sometimes there is an empty line between the generated methods, sometime not:
![image](https://user-images.githubusercontent.com/3104253/108234903-91ef6700-7145-11eb-986c-f39cf5da4813.png)

There should be an empty line above the yellow line.

**Comment by AArnott** [comment] 2021-02-17 16:40
Duplicate of #23

**Closed by AArnott** 2021-02-17 16:40 UTC
