### ISSUE TITLE
Syntax sugar for single out parameter as the method return value

### ISSUE THREAD

**Issue by rgl** [microsoft/CsWin32#474] opened 2022-01-02 17:39 UTC
**Is your feature request related to a problem? Please describe.**

It would be pretty nice to have some kind of syntax sugar for returning a single `out` parameter as the wrapped method return value.

**Describe the solution you'd like**

For example, as-of v0.1.619-beta, the [IDesktopWallpaper.GetBackgroundColor](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-idesktopwallpaper-getbackgroundcolor) wrapper is used as:

```csharp
private static void DumpDisplays(IDesktopWallpaper desktopWallpaper)
{
  desktopWallpaper.GetBackgroundColor(out uint backgroundColorNative);
}
```

With syntax sugar, it would be:

```csharp
private static void DumpDisplays(IDesktopWallpaper desktopWallpaper)
{
  var backgroundColor = desktopWallpaper.GetBackgroundColor();
}
```

**Describe alternatives you've considered**

Doing my own extension methods.

**Comment by jnm2** [comment] 2022-01-03 22:18
I think this is the same as https://github.com/microsoft/CsWin32/issues/341.

**Comment by AArnott** [comment] 2022-01-04 03:24
Agreed. This is a duplicate of #341.

**Closed by AArnott** 2022-01-04 03:24 UTC
Labels: enhancement
