### ISSUE TITLE
GetSize and GetPixelSize methods on ID2D1RenderTarget need special ABI handling

### ISSUE THREAD

**Issue by Shkyrockett** [microsoft/CsWin32#731] opened 2022-10-12 02:59 UTC
## Actual behavior

`ID2D1RenderTarget.EndDraw` does not return a needed `HRESULT`, and `ID2D1RenderTarget.GetSize`, and `ID2D1RenderTarget.GetPixelSize` throw System.AccessViolationException exceptions when accessed because they are also not returning `HRESULT`s.

## Expected behavior

The `EndDraw`, `GetSize`, and `GetPixelSize` methods should return `HRESULT` in `ID2D1RenderTarget` and inherited interfaces, when using `"allowMarshaling": true`. Maybe these need to be marked as `[PreserveSig]`?

`ID2D1RenderTarget.EndDraw` should return an `HRESULT` so the result can be used to tell if the draw attempt failed and Direct2D needs to be reinitialized because of a display reset. See https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1rendertarget#remarks

Both `ID2D1RenderTarget.GetSize`, and `ID2D1RenderTarget.GetPixelSize` throw `System.AccessViolationException` exceptions when called using the current method signatures which return `D2D_SIZE_F` or `D2D_SIZE_U` respectively. Changing the methods to return `HRESULT` fixes the exception. Friendly overload extensions that do return `D2D_SIZE_F` or `D2D_SIZE_U` would be helpful for these methods.

## Repro steps

1. `NativeMethods.txt` content:
```
ID2D1RenderTarget
S_OK
CreateDCW
ID2D1Factory7
D2D1CreateFactory
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "allowMarshaling": true,
  "className": "PInvoke",
  "emitSingleFile": false,
  "public": true,
  "wideCharOnly": true
}
```

3. Any of your own code that should be shared?

Minimal repro:

```csharp
using System.Runtime.InteropServices;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Direct2D;
using Windows.Win32.Graphics.Direct2D.Common;
using Windows.Win32.Graphics.Dxgi.Common;
using Windows.Win32.Graphics.Gdi;

unsafe
{
    var direct2dFactory = PInvoke.D2D1CreateFactory(D2D1_FACTORY_TYPE.D2D1_FACTORY_TYPE_SINGLE_THREADED, typeof(ID2D1Factory7).GUID, new D2D1_FACTORY_OPTIONS(), out var factory) switch { var h when h == HRESULT.S_OK => factory as ID2D1Factory7, _ => throw new Exception("Unspecified Error") };
    var dcRenderTarget = InitializeDirect2DDCRenderTarget(direct2dFactory!);

    var hdc = PInvoke.CreateDCW("DISPLAY", string.Empty, string.Empty, new()).DangerousGetHandle();
    bindDc(dcRenderTarget, new HDC(hdc), new());

    dcRenderTarget.BeginDraw();

    var pSize = dcRenderTarget.GetPixelSize(); // System.AccessViolationException exception here.
    var size = dcRenderTarget.GetSize(); // System.AccessViolationException exception here.

    dcRenderTarget.EndDraw(); // This ought to return an HRESULT. See https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1rendertarget#remarks

    PInvoke.DeleteDC(new(hdc));
}

static unsafe ID2D1DCRenderTarget InitializeDirect2DDCRenderTarget(ID2D1Factory7 direct2dFactory)
{
    direct2dFactory.CreateDCRenderTarget(
        new D2D1_RENDER_TARGET_PROPERTIES()
        {
            type = D2D1_RENDER_TARGET_TYPE.D2D1_RENDER_TARGET_TYPE_DEFAULT,
            pixelFormat = new D2D1_PIXEL_FORMAT()
            {
                format = DXGI_FORMAT.DXGI_FORMAT_B8G8R8A8_UNORM,
                alphaMode = D2D1_ALPHA_MODE.D2D1_ALPHA_MODE_IGNORE
            },
            dpiX = 0,
            dpiY = 0,
            usage = D2D1_RENDER_TARGET_USAGE.D2D1_RENDER_TARGET_USAGE_GDI_COMPATIBLE,
            minLevel = D2D1_FEATURE_LEVEL.D2D1_FEATURE_LEVEL_DEFAULT
        }, out var dcRenderTarget);
    Marshal.ReleaseComObject(direct2dFactory);
    return dcRenderTarget;
}

static unsafe void bindDc(ID2D1DCRenderTarget dcRenderTarget, HDC hdc, in RECT rect)
{
    fixed (RECT* r = &rect)
    {
        dcRenderTarget.BindDC(hdc, r);
    }
}
```

The code above should be rewritten to the following if the methods returned HRESULTS:

```csharp
using System.Runtime.InteropServices;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Direct2D;
using Windows.Win32.Graphics.Direct2D.Common;
using Windows.Win32.Graphics.Dxgi.Common;
using Windows.Win32.Graphics.Gdi;

unsafe
{
    var direct2dFactory = PInvoke.D2D1CreateFactory(D2D1_FACTORY_TYPE.D2D1_FACTORY_TYPE_SINGLE_THREADED, typeof(ID2D1Factory7).GUID, new D2D1_FACTORY_OPTIONS(), out var factory) switch { var h when h == HRESULT.S_OK => factory as ID2D1Factory7, _ => throw new Exception("Unspecified Error") };
    var dcRenderTarget = InitializeDirect2DDCRenderTarget(direct2dFactory!);

    var hdc = PInvoke.CreateDCW("DISPLAY", string.Empty, string.Empty, new()).DangerousGetHandle();
    bindDc(dcRenderTarget, new HDC(hdc), new());

    dcRenderTarget.BeginDraw();

    _ = dcRenderTarget.GetPixelSize(out var pSize);
    _ = dcRenderTarget.GetSize(out var size);

    var result = dcRenderTarget.EndDraw();
    if (result == HRESULT.D2DERR_RECREATE_TARGET)
    {
        // Recreate resources if they have become invalid. See https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1rendertarget#remarks
        dcRenderTarget = InitializeDirect2DDCRenderTarget(direct2dFactory);
    }

    PInvoke.DeleteDC(new(hdc));
}

static unsafe ID2D1DCRenderTarget InitializeDirect2DDCRenderTarget(ID2D1Factory7 direct2dFactory)
{
    direct2dFactory.CreateDCRenderTarget(
        new D2D1_RENDER_TARGET_PROPERTIES()
        {
            type = D2D1_RENDER_TARGET_TYPE.D2D1_RENDER_TARGET_TYPE_DEFAULT,
            pixelFormat = new D2D1_PIXEL_FORMAT()
            {
                format = DXGI_FORMAT.DXGI_FORMAT_B8G8R8A8_UNORM,
                alphaMode = D2D1_ALPHA_MODE.D2D1_ALPHA_MODE_IGNORE
            },
            dpiX = 0,
            dpiY = 0,
            usage = D2D1_RENDER_TARGET_USAGE.D2D1_RENDER_TARGET_USAGE_GDI_COMPATIBLE,
            minLevel = D2D1_FEATURE_LEVEL.D2D1_FEATURE_LEVEL_DEFAULT
        }, out var dcRenderTarget);
    Marshal.ReleaseComObject(direct2dFactory);
    return dcRenderTarget;
}

static unsafe void bindDc(ID2D1DCRenderTarget dcRenderTarget, HDC hdc, in RECT rect)
{
    fixed (RECT* r = &rect)
    {
        dcRenderTarget.BindDC(hdc, r);
    }
}
```
### Context

- CsWin32 version: 0.2.63-beta
- Win32Metadata version: 35.0.14-preview
- Target Framework: net6.0-windows
- LangVersion: 10.0

**Comment by AArnott** [comment] 2022-10-14 21:51
Note to self: our fix in CsWin32 will require that we apply similar transformations that the rust projection applies, as described here:
https://github.com/microsoft/win32metadata/issues/636#issuecomment-1039494191
https://github.com/microsoft/win32metadata/issues/636#issuecomment-1232025001

To avoid user confusion though, we may want to adjust our friendly overloads to look like the documented signature (in effect, reversing the transformation).

**Comment by AArnott** [comment] 2022-10-14 21:57
@Shkyrockett Can you confirm that once fixed, you're expecting pixel sizes of 0 to come out of these to get size methods? When I manually apply the prescribed fix, I'm getting 0,0 from both methods.

**Comment by AArnott** [comment] 2022-10-27 03:28
Duplicate of #167

**Closed by AArnott** 2022-10-27 03:28 UTC
Labels: bug
