### ISSUE TITLE
How to use CsWin32 generated interface / using newer Win32Metadata leads to compile time error

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [microsoft/CsWin32#135] opened 2021-02-20 07:53 UTC
Firstly thanks for your cool project!

We're currently using

> &lt;PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.17134.1000" /&gt;

to access Sensor apis in a .NET Core 3.1 WinForms application.

We would like to migrate to .NET 5 but sadly only newer TargetFrameworks (e.g. net5-windows10.0.17763.0) are supported and our customers are still using older Windows 10 versions (special hardware).

Generating `ISensorManager` and other types using CsWin32 works. Where I still fail is at casting the COM object to ISensorManager:

> Guid CLSID_SensorManager = new Guid("77A1C827-FCD2-4689-8915-9D613CC5FA3E");
Type type = Type.GetTypeFromCLSID(CLSID_SensorManager, true);
var sensorManager = Activator.CreateInstance(type);
var x = (ISensorManager) sensorManager;

>"Unable to cast COM object of type 'System.__ComObject' to class type 'Microsoft.Windows.Sdk.ISensorManager'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface."

I tried to include newer Win32Metadata but anything newer than preview.5 leads to compile time errors even though unsafe code is allowed for the project:

> &lt;PackageReference Include="Microsoft.Windows.SDK.Win32Metadata" Version="10.0.19041.5-preview.20" /&gt;

> Microsoft.Windows.CsWin32.SourceGenerator\PWSTR.g.cs(21,41,21,47): error CS0214: Zeiger und Puffer fester Größe können nur in einem unsicheren Kontext verwendet werden. (pointers & buffers of fixed size can only be used in an unsafe context)

Any help would be very much appreciated!

**Comment by AArnott** [comment] 2021-02-20 16:44
> using newer Win32Metadata leads to compile time error

Duplicate of #121 

> How to use CsWin32 generated interface

We don't generate interfaces. We generate structs that look like the COM interface.
See #86 for more on this and our future plans.

**Closed by AArnott** 2021-02-20 16:44 UTC
