### ISSUE TITLE
Source Generator Generates Structs Instead of Interfaces

### ISSUE THREAD

**Issue by v-alje** [microsoft/CsWin32#52] opened 2021-01-22 18:44 UTC
The source generator currently generates structs instead of interfaces. This makes things a little difficult when an API relies on being able to use inheritance and multiple interfaces, for example [DWriteCreateFactory](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-dwritecreatefactory):

NativeMethods.txt
```
DWRITE.*
IUnknown
IDWriteFactory
IDWriteFactory1
IDWriteFactory2
IDWriteFactory3
IDWriteFactory4
IDWriteFactory5
IDWriteFactory6
IDWriteFactory7
```

Program.cs
```csharp
using Microsoft.Windows.Sdk;

namespace InterFaceGenerationRepro
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            IDWriteFactory factory;
            HRESULT result = PInvoke.DWriteCreateFactory(DWRITE_FACTORY_TYPE.DWRITE_FACTORY_TYPE_SHARED, typeof(IDWriteFactory).GUID, out factory);
        }
    }
}
```

The IDWriteFactory interface is based off of IUnknown, and has seven other interfaces that can be swapped in to provide additional methods that can be called, by changing the GUID in the DWriteCreateFactory iid parameter to communicate which interface to use.

Expected:
The source generator should generate interfaces with full inheritance hierarchy for interfaces.

Actual:
The source generator currently generates structs in place of interfaces, causing DWriteCreateFactory's factory out parameter to not be able to cast to any of the IDWriteFactory interfaces to the defined IUnknown type.

**Comment by AArnott** [comment] 2021-01-22 22:24
Thanks for the feedback. The current behavior is intentional but we want to offer interface generation as an option.
Once we get into interfaces, marshaling of structs is required, which unravels a bunch of the rest of the generated code. We do want to do this as an option variant of code gen.

Duplicate of #26

**Closed by AArnott** 2021-01-22 22:24 UTC
