### ISSUE TITLE
GetModuleHandle returns an owned SafeHandle

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/CsWin32#616] opened 2022-07-21 23:13 UTC
## Actual behavior

GetModuleHandle's safe overload returns an owned safe handle, which would free the HINSTANCE .

## Expected behavior

The handle shouldn't be owned as GetModuleHandle doesn't ref count. https://docs.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlew#remarks

## Repro steps

1. `NativeMethods.txt` content:
```
GetModuleHandle
```

**Comment by AArnott** [comment] 2022-07-23 03:25
Duplicate of https://github.com/microsoft/win32metadata/issues/921

**Closed by AArnott** 2022-07-23 03:25 UTC
Labels: bug
