### ISSUE TITLE
Generated code not compiling with latest win32metadata

### ISSUE THREAD

**Issue by zgabi** [microsoft/CsWin32#131] opened 2021-02-18 22:17 UTC
Compile error:
Error	CS0214	Pointers and fixed size buffers may only be used in an unsafe context	
project\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\PWSTR.cs

Microsoft.Windows.SDK.Win32Metadata Version: 10.0.19041.5-preview.20

**Comment by AArnott** [comment] 2021-02-19 00:28
Duplicate of #121

**Comment by AArnott** [comment] 2021-02-19 00:29
FYI: in general we want you to be able to update metadata independently of the source generator, but the metadata is not stable yet and most updates require compensating changes to the projections to work.

**Closed by AArnott** 2021-02-19 00:28 UTC
