### ISSUE TITLE
Installing Microsoft.Windows.SDK.Win32Metadata causes Microsoft.Windows.Sdk namespace to disappear.

### ISSUE THREAD

**Issue by MikeYeager** [microsoft/CsWin32#289] opened 2021-06-08 17:11 UTC
I was notified that issue #384 was closed via #435 (an update to Microsoft.Windows.SDK.Metadata in v10.0.19041.166-preview), but when I install that NuGet package, the Microsoft.Windows.Sdk namespace disappears. The documentation suggests I should install this package in order to get the latest metadata.

    _Newer metadata
    To update the metadata used as the source for code generation, you may install a newer 
    Microsoft.Windows.SDK.Win32Metadata package:

    dotnet add package Microsoft.Windows.SDK.Win32Metadata -pre_

## Expected behavior

Expect that adding the Microsoft.Windows.SDK.Metadata package would give me the latest metadata without breaking the project.

### Context

- CsWin32 version:  0.1.422-beta
- Win32Metadata version (if explicitly set by project): 0.0.19041.166-preview
- Target Framework: .NET 5
- `LangVersion` (if explicitly set by project): n/a

Do I need to wait for an update to CsWin32?
Thank You,
Mike

**Comment by jnm2** [comment] 2021-06-08 18:50
Perhaps https://github.com/microsoft/CsWin32/issues/274 covers this?

**Comment by AArnott** [comment] 2021-06-09 20:53
Duplicate of #131: updating to metadata that the CsWin32 generator has not been tested with is unsupported, and likely to fail while the metadata is significantly changing.

**Closed by AArnott** 2021-06-09 20:53 UTC
Labels: bug
