### ISSUE TITLE
`ReadFile` and `WriteFile` require unsafe code

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/CsWin32#857] opened 2023-02-08 18:52 UTC
## Actual behavior

In order to use `PInvoke.ReadFile` and `PInvoke.WriteFile`, I am required to use `unsafe` and `fixed` logic for the `NativeOverlapped` parameter. This is in contrast to `PInvoke.GetOverlappedResult` which uses an `in` flag on the parameter.

For example:

```cs
unsafe
{
    fixed (byte* ptr = buffer)
    fixed (NativeOverlapped* overlapped = &_writeOverlapped)
    {
        if (PInvoke.WriteFile(_handle, ptr, (uint)count, &bytesWrote, overlapped))
            return;
    }
}

// handle overlapped behavior
if (Marshal.GetLastWin32Error() is not ERROR_IO_PENDING)
    throw new Win32Exception();

if (!PInvoke.GetOverlappedResult(_handle, _writeOverlapped, out bytesWrote, true))
    throw new Win32Exception();
```

OR

```cs
unsafe
{
    fixed (byte* ptr = buffer)
    fixed (NativeOverlapped* overlapped = &_writeOverlapped)
    {
        if (PInvoke.WriteFile(_handle, ptr, (uint)count, &bytesWrote, overlapped))
            return;

        // handle overlapped behavior
        if (Marshal.GetLastWin32Error() is not ERROR_IO_PENDING)
            throw new Win32Exception();

        if (!PInvoke.GetOverlappedResult(_handle, *overlapped, out bytesWrote, true))
            throw new Win32Exception();
    }
}
```

## Expected behavior

Ideally, I would be able to pass the `NativeOverlapped` objects as `in` parameters like I can with `GetOverlappedResult`:

```cs
if (PInvoke.WriteFile(_handle, buffer, (uint)count, out bytesWrote, _writeOverlapped))
    return;

// handle overlapped behavior
if (Marshal.GetLastWin32Error() is not ERROR_IO_PENDING)
    throw new Win32Exception();

if (!PInvoke.GetOverlappedResult(_handle, _writeOverlapped, out bytesWrote, true))
    throw new Win32Exception();
```

## Repro steps

1. `NativeMethods.txt` content:
```
ReadFile
WriteFile
```

### Context

- CsWin32 version: `0.2.188-beta`
- Target Framework: `net7.0`

**Comment by AArnott** [comment] 2023-02-09 13:13
> Ideally, I would be able to pass the NativeOverlapped objects as in parameters like I can with GetOverlappedResult

The `ReadFile` and `WriteFile` methods define `lpOverlapped` with `[Optional][In][Out]` attributes, which is why CsWin32 surfaces it as a pointer: it's _optional_. Using `ref` would force you to pass a value in (except for one very poorly known and syntax-heavy technique). It's just a limitation of the C# language that `ref` parameters cannot also be optional.

The buffer pointer might have been changed to `Span<byte>` for the friendly overload that CsWin32 generates, but because it is typed as `void*` instead of `byte*`, that precludes that as well.

> `ClearCommError` is also the same way

Same answer: these out parameters are optional.

**Comment by colejohnson66** [comment] 2023-02-10 14:19
That makes sense. However, I think `nNumberOfBytesToWrite` should still be an `out uint`. If the user doesn't want the "optional, out" parameter, they could just use a discard (`out _`).

I would possibly suggest generating overloads (one with a `ref NativeOverlapped` and one without), but that seems clunky and prone to breakage or manual tweaking per method.

A `ref NativeOverlapped` parameter would still work; I could just pass `ref Unsafe.NullRef<NativeOverlapped>()` if I wanted a `NULL` for the parameter.

**Comment by AArnott** [comment] 2023-02-10 15:21
>  I could just pass `ref Unsafe.NullRef<NativeOverlapped>()` if I wanted a NULL for the parameter.

Yes, that's the true but very undiscoverable solution. 

Additional overloads could fix this, and it's something you could actually do within your own project since the PInvoke class is partial. Doing it within CsWin32 would typically need a general policy for handling so we can solve 'the whole problem' rather than just two methods that happened to get noticed. Knowing when it makes sense to treat an optional parameter as mandatory so that `out` can be used isn't something we can generally do given what's in the metadata today. And while `out _` works, it passes a non-NULL pointer into the native method, and for some methods, that changes behavior and/or perf characteristics of the method.

**Comment by colejohnson66** [comment] 2023-02-10 21:47
> Doing it within CsWin32 would typically need a general policy for handling so we can solve 'the whole problem' rather than just two methods that happened to get noticed.

Hence, my remark about it being "clunky and prone to breakage".

**Comment by AArnott** [comment] 2023-02-10 22:52
I'm going to close the issue as By Design. If you have further insights on this, feel free to add comments here for review.

**Closed by AArnott** 2023-02-10 22:52 UTC
Labels: bug
