### ISSUE TITLE
Generated code doesn't not compile with LangVersion=preview (C#11)

### ISSUE THREAD

**Issue by meziantou** [microsoft/CsWin32#688] opened 2022-09-11 01:29 UTC
## Actual behavior

```
CS8170 Struct members cannot return 'this' or other instance members by reference
```
```
CS8347 Cannot use a result of 'MemoryMarshal.CreateSpan<char>(ref char, int)' in this context because it may expose variables referenced by parameter 'reference' outside of their declaration scope
```

The generated method:

````
/// <summary>
/// Gets this inline array as a span.
/// </summary>
/// <remarks>
/// ⚠ Important ⚠: When this struct is on the stack, do not let the returned span outlive the stack frame that defines it.
/// </remarks>
internal Span<char> AsSpan() => MemoryMarshal.CreateSpan(ref _0, 256);
````

May be related to https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/breaking-changes/compiler%20breaking%20changes%20-%20dotnet%207?WT.mc_id=DT-MVP-5003978#method-ref-struct-return-escape-analysis-depends-on-ref-escape-of-ref-arguments

## Expected behavior

The generated code compiles when targeting C# 11

## Repro steps

`csproj` content:

````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.2.46-beta">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
````

`NativeMethods.txt` content:
 
```
RmRegisterResources
RmStartSession
RmJoinSession
RmEndSession
RmGetList
RmShutdown
RmRestart
GetProcessTimes
```

### Context

- CsWin32 version: `0.2.46-beta` (latest on NuGet.org)
- Target Framework: net6.0;net7.0
- `LangVersion`: preview (C# 11)
- Compiler version: '4.4.0-1.22403.13 (ebbf56c2)' (.NET 7 preview 7)

**Comment by AArnott** [comment] 2022-09-13 03:27
Duplicate of #637

**Closed by AArnott** 2022-09-13 03:27 UTC
Labels: bug
