### ISSUE TITLE
The generated Next method on IEnumSearchScopeRules takes an array where a pointer to an array is expected

### ISSUE THREAD

**Issue by skippy10110** [microsoft/CsWin32#333] opened 2021-07-17 18:58 UTC
## Actual behavior

The [Next](https://docs.microsoft.com/en-us/windows/win32/api/searchapi/nf-searchapi-ienumsearchscoperules-next) method on the [IEnumSearchScopeRules](https://docs.microsoft.com/en-us/windows/win32/api/searchapi/nn-searchapi-ienumsearchscoperules) interface is generated to take in a normal array of [ISearchScopeRule](https://docs.microsoft.com/en-us/windows/win32/api/searchapi/nn-searchapi-isearchscoperule) where a pointer to an array is expected. This doesn't work and tends to segfault.

## Expected behavior

The Next method is supposed to take in a pointer to an array that is then filled with results. The celt parameter indicates its size. I'm not an interop expert so I can't say what the proper method definition should be.

## Repro steps

1. `NativeMethods.txt` content:
```
IEnumSearchScopeRules
```

2. `NativeMethods.json` content (if present):

3. Any of your own code that should be shared?

### Context

- CsWin32 version: v0.1.506-beta
- Win32Metadata version (if explicitly set by project): n/a
- Target Framework: net5.0-windows
- `LangVersion` (if explicitly set by project): n/a

Here's the definition I see in ILSpy for win32metadata. I haven't used ILSpy before, but if I'm understanding what this is saying it looks correct to me.

    unsafe HRESULT Next([In] uint celt, [Out][NativeArrayInfo(CountParamIndex = 0)] ISearchScopeRule* pprgelt, [Optional][In][Out] uint* pceltFetched);

Here's the method that CsWin32 generates:

    unsafe void Next(uint celt, win32.System.Search.ISearchScopeRule[] pprgelt, [Optional()]uint* pceltFetched);

This is what I change the generated method to in order to make it work:

    unsafe void Next(uint celt, out ISearchScopeRule pprgelt, [Optional] uint* pceltFetched);

This isn't quite the correct definition, but it works around my issue for now as I'm only ever requesting 1 at a time. Then I'm able to call it like so:

    enumSearchScopeRules.Next(1, out var searchScopeRule, null);

**Comment by skippy10110** [comment] 2021-07-18 10:59
I found the documentation for `pprgelt` confusing btw, it says this:

> pprgelt
> Type: ISearchScopeRule**
> On return, contains a pointer to an array of ISearchScopeRule elements.

The method only works if I pass in a pointer to an array that has already been allocated. `pprgelt` contains a pointer to an array "on return" because that's exactly the pointer you provided as input.

That tripped me up when I was first investigating the issue and trying to understand what was wrong with the generated method and what it should be instead. I could be totally misreading that, this is new to me, but wanted to include that context in case it trips anyone else up too.

**Comment by AArnott** [comment] 2021-08-18 16:15
I agree the docs were confusing. Here is my attempt to fix them: https://github.com/MicrosoftDocs/sdk-api/pull/871

I believe the generated C# method is correct. How were you using it? This is the intended use:

```cs
var array = new ISearchScopeRule[1];
enumSearchScopeRules.Next(array, null);
ISearchScopeRule result = array[0];
```

This invokes the extension method that just adds `array.Length` as an argument to the original method. But note the array must be pre-allocated and passed in.

**Comment by skippy10110** [comment] 2021-08-18 16:56
Thanks for the documentation fix!

I wasn't use the extension method before, I missed that it existed. I just updated my code to use that and got a segfault again. Here's the full method that I have:

````csharp
public static unsafe void Next2(this IEnumSearchScopeRules @this, uint celt, out ISearchScopeRule pprgelt, out uint pceltFetched)
{
    fixed(uint* pceltFetchedLocal = &pceltFetched)
    {
        var array = new ISearchScopeRule[1];
        @this.Next(array, pceltFetchedLocal);
        pprgelt = array[0];
    }
}
````

I needed to further wrap the Next extension method to remove the raw pointers as I'm ultimately calling this function from Powershell.

This is the error that I see:

````
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.StubHelpers.MngdSafeArrayMarshaler.ClearNative(IntPtr, System.Object ByRef, IntPtr)
   at Windows.Win32.System.Search.IEnumSearchScopeRules.Next(UInt32, Windows.Win32.System.Search.ISearchScopeRule[], UInt32*)
   at Windows.Win32.FriendlyOverloadExtensions.Next(Windows.Win32.System.Search.IEnumSearchScopeRules, Windows.Win32.System.Search.ISearchScopeRule[], UInt32*)
   at Windows.Win32.FriendlyOverloadExtensions.Next2(Windows.Win32.System.Search.IEnumSearchScopeRules, UInt32, Windows.Win32.System.Search.ISearchScopeRule ByRef, UInt32 ByRef)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at ComHelper.InvokeMethod(System.Type, System.String, System.Object, System.Object[])
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.Type, System.String, System.Object, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon)
   at System.Management.Automation.Interpreter.DynamicInstruction`6[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
````

That's truncated a bit as the full stack trace is fairly long.

For reference, this is the actual code that I currently have that doesn't segfault:

````csharp
public static partial class FriendlyOverloadExtensions
{
    public static unsafe void Next2(this IEnumSearchScopeRules @this, uint celt, out ISearchScopeRule pprgelt, out uint pceltFetched)
    {
        fixed(uint* pceltFetchedLocal = &pceltFetched)
        {
            @this.Next(celt, out pprgelt, pceltFetchedLocal);
        }
    }
}

namespace System.Search
{
    //TODO: This is a copy of the generated code for IEnumSearchScopeRules, but with the Next method patched up
    //TODO: https://github.com/microsoft/CsWin32/issues/333
    [Guid("AB310581-AC80-11D1-8DF3-00C04FB6EF54"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IEnumSearchScopeRules
    {
        unsafe void Next(uint celt, out ISearchScopeRule pprgelt, [Optional] uint* pceltFetched);
        void Skip(uint celt);
        void Reset();
        void Clone(out IEnumSearchScopeRules ppenum);
    }
}
````

**Comment by AArnott** [comment] 2021-08-18 18:33
I suspect we may be lacking attributes on the `pprgelt` parameter so the .NET marshaler knows how to marshal the array. I'm not sure what attributes would be necessary though. If you can give me a minimal repro project I can play with it. 
Alternatively if you copy and paste the interface we generate to your own code and add `[Out]` (or play with `[MarshalAs(...)]`) attributes on that parameter, and if you find something that works, please share.

**Comment by AArnott** [comment] 2021-08-18 19:44
Duplicate of #269.

**Closed** 2021-08-18 19:45 UTC
Labels: bug

**Comment by skippy10110** [comment] 2021-08-20 00:22
Thanks for the issue link. I can confirm that the following signature fixes my issue:

````csharp
unsafe void Next(uint celt, [Out, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 0)] ISearchScopeRule[] pprgelt, [Optional()] uint* pceltFetched);
````

This is exactly the generated signature, with only the [Out] and [MarshalAs] added as per #269.
