### ISSUE TITLE
SHAppBarMessage not generated for ARM64 platform.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/CsWin32#512] opened 2022-03-04 00:01 UTC
## Actual behavior

Compiling a .NET 6 class library using SHAppBarMessage in Debug/Release - ARM64 results in:

PInvoke005 This API is only available when targeting a specific CPU architecture. AnyCPU cannot generate this API.

## Expected behavior

API is generated successfully.

## Repro steps

1. `NativeMethods.txt` content:
```
SHAppBarMessage
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.1.635-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net6.0-10.0.22000.0
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by jlaanstra** [comment] 2022-03-04 01:23
Seeing the same problem for Shell_NotifyIconGetRect and Shell_NotifyIcon

**Comment by AArnott** [comment] 2022-03-09 05:19
Duplicate of #505

**Closed by AArnott** 2022-03-09 05:19 UTC
Labels: bug

**Comment by jlaanstra** [comment] 2022-03-09 06:08
@AArnott are you sure this is a dupe of #505? I don't see any mention of ARM64 in there. It mentions that it doesn't work for AnyCPU, but I am not building for AnyCPU.

**Comment by AArnott** [comment] 2022-03-09 15:11
Oh, you're right. It's actually a dupe of #494. Basically a bug in msbuild that requires a workaround in your project file.
