### ISSUE TITLE
Make GetWindowLong/SetWindowLong Dynamic

### ISSUE THREAD

**Issue by lonitra** [microsoft/CsWin32#690] opened 2022-09-12 16:21 UTC
**Is your feature request related to a problem? Please describe.**
WinForms supports both 32/64-bit environment. APIs `GetWindowLong`/`SetWindowLong` currently return `int` which in 64-bit environment will return incorrect results.

**Describe the solution you'd like**
Make these APIs dynamic by updating return value of these APIs to `nint` and do a check on the environment. Something like:
```c#
public static nint GetWindowLong(HWND hwnd, WINDOW_LONG_PTR_INDEX nIndex)
        {
            nint result = Environment.Is64BitProcess
                ? GetWindowLongPtrW(hwnd nIndex)
                : GetWindowLongW(hwnd, nIndex);
            return result;
        }
```

**Comment by elachlan** [comment] 2022-09-12 23:39
@lonitra, see the discussion in https://github.com/dotnet/winforms/issues/7445.

**Comment by AArnott** [comment] 2022-09-13 15:25
Duplicate of #343.

**Closed by AArnott** 2022-09-13 15:25 UTC
Labels: enhancement
