### ISSUE TITLE
CsWin32 generates unsafe and more complex signature to deal with than manual PiInvoke

### ISSUE THREAD

**Issue by smaillet** [microsoft/CsWin32#483] opened 2022-01-18 17:27 UTC
## Actual behavior

The idea behind CsWin32 is supposed to be a consistent single source of truth for Win32 PInvoke so we don't need to deal with it manually. However, that's an insanely tall order (and I'd argue 100% impossible to do in a purely automated fashion) resulting in lot's of very poor experiences. Take for instance any method that returns a string and length (for example [GetCurrentApplicationUserModelId](https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-getcurrentapplicationusermodelid).

## Expected behavior
Expected a usable simple API call that blends well into C# and .NET equivalent to what we'd do manually like the following:
```C#
[DllImport( "kernel32.dll" )]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
internal static extern int GetCurrentApplicationUserModelId( [In, Out] ref uint aumIDLen, [MarshalAs( UnmanagedType.LPWStr, SizeParamIndex = 1 ), Out] out string aumId );
```

Instead what it generates is a vastly more complex to use signature with a custom, and undocumented, PWSTR type leaving all the work that the marshaller could do for you to the app developer...

## Repro steps

1. `NativeMethods.txt` content:
```
GetCurrentApplicationUserModelId
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.1.619-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net6.0-windows10.0.20348.0
- `LangVersion` (if explicitly set by project): [e.g. `9`] - not set but will be 10

**Comment by AArnott** [comment] 2022-01-25 17:53
Our goal is to do even better than your expected behavior. 
We don't rely (much) on the CLR marshaler for performance reasons and compatibility across runtimes. However we generate friendly overloads wherever possible. In the case of the API you refer to, the metadata defines it this way:

```cs

[DllImport("KERNEL32", ExactSpelling = true)]
public unsafe static extern int GetCurrentApplicationUserModelId([In][Out] uint* applicationUserModelIdLength, [Optional][Out][NativeArrayInfo(CountParamIndex = 0)] PWSTR applicationUserModelId);
```

This is great, because it means CsWin32 can theoretically generate a friendly overload with this signature:
```cs
public static int GetCurrentApplicationUserModelId(out string applicationUserModelId);
```

Now, given we don't know the expected length of the buffer it's more likely we'll expose a friendly overload more like this:

```cs
public static int GetCurrentApplicationUserModelId(ref Span<char> applicationUserModelId);
```

#271 already tracks leveraging the hints that the metadata gives us to improve this, so I'm closing this issue as a duplicate. 

Thank you for your feedback.

**Closed by AArnott** 2022-01-25 17:53 UTC
Labels: bug
