### ISSUE TITLE
Functions taking HDC do not have friendly overloads taking SafeHandle

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#1060] opened 2023-10-01 17:02 UTC
Even though CsWin32 currently doesn't happen to provide DeleteDCSafeHandle or ReleaseDCSafeHandle, I do have such classes that I'd like to pass as SafeHandle without having to do the whole boilerplate dance:

```cs
bool thing1NeedsRelease = false;
thing1.DangerousAddRef(ref thing1NeedsRelease);
try
{
    bool thing2NeedsRelease = false;
    thing2.DangerousAddRef(ref thing2NeedsRelease);
    try
    {
        PInvoke.BitBlt((HDC)thing1.DangerousGetHandle(), ..., (HDC)thing2.DangerousGetHandle(), ...);
    }
    finally
    {
        if (thing2NeedsRelease) thing2.DangerousRelease();
    }
}
finally
{
    if (thing1NeedsRelease) thing1.DangerousRelease();
}
```

This usability issue afflicts BitBlt, CreateDIBSection, DrawIconEx, SelectObject, maybe others. For me, CsWin32 is about not having to intersperse interesting logic with .NET native interop boilerplate. It would be very much in that spirit to always provide SafeHandle overloads any time there is a handle wrapper struct.

### Context

- CsWin32 version: 0.3.46-beta
- Target Framework: net3.5;net4.8;net6.0-windows
- `LangVersion` (if explicitly set by project): 11

**Comment by AArnott** [comment] 2023-10-02 15:05
Duplicate of #1049 (but I'll rename it to make this more obvious.)

**Closed by AArnott** 2023-10-02 15:05 UTC
Labels: bug
