### ISSUE TITLE
Generate code that compiles when targeting .NET Core 3.1

### ISSUE THREAD

**Issue by Craftplacer** [microsoft/CsWin32#373] opened 2021-08-22 10:45 UTC
**Is your feature request related to a problem? Please describe.**
While this library is perfectly installable on .NET Core 3.1, problems arise when building, where the source generator adds platform attributes which aren't made public yet.

**Describe the solution you'd like**
Possible exclusion of those attributes when running on versions earlier than 5.0 or find another alternative.

**Describe alternatives you've considered**
None at the moment.

**Comment by jnm2** [comment] 2021-08-22 16:18
I wonder if this will be fixed by the fix for https://github.com/microsoft/CsWin32/issues/365. Could you specify which attributes specifically you needed to define yourself in order to get CsWin32 working on netcoreapp3.1?

**Comment by Craftplacer** [comment] 2021-08-24 04:34
Currently the generator adds `SupportedOSPlatformAttribute` which results in `CS0122` at build-time.

Trying to define my own `System.Runtime.Versioning.SupportedOSPlatformAttribute` results in #365.

This certainly seems closely related to that issue, so possibly this is a duplicate.

**Comment by jnm2** [comment] 2021-08-24 14:09
Cool. The workaround is to declare `System.Runtime.Versioning.SupportedOSPlatformAttribute` (as internal) in every project which uses CsWin32.

**Comment by AArnott** [comment] 2021-08-25 13:51
Duplicate of #365

**Closed by AArnott** 2021-08-25 13:51 UTC
Labels: enhancement
