### ISSUE TITLE
GetModuleHandle incorrectly returns a FreeLibrarySafeHandle

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWin32#1068] opened 2023-10-15 19:26 UTC
> The GetModuleHandle function returns a handle to a mapped module without incrementing its reference count. However, if this handle is passed to the [FreeLibrary](https://learn.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-freelibrary) function, the reference count of the mapped module will be decremented. Therefore, do not pass a handle returned by GetModuleHandle to the FreeLibrary function. Doing so can cause a DLL module to be unmapped prematurely.

https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlea

**Comment by AArnott** [comment] 2023-10-20 18:48
Duplicate of #644, which by the way was resolved by honoring `DoNotRelease` attributes in the metadata. While CsWin32's friendly overload does return a safe handle, it's an object that will _not_ release the handle (it's created with `ownsHandle: false`). 

The `SafeHandle` return type is believed to be useful for other reasons (e.g. for passing to another API that requires a SafeHandle parameter type), even if it never releases the native handle.

**Closed by AArnott** 2023-10-20 18:48 UTC
Labels: bug
